import React,{useState} from 'react';
import {createPlanningDemo} from '../domain/planning-demo.js';
import {dayKey,heatLevel} from '../domain/planning.js';
import '../planning.css';
import Icon from './Icon.jsx';
export default function CompanyDemo({onExit}){
 const [view,setView]=useState('Inicio'),[day,setDay]=useState(14);const month=dayKey(new Date()).slice(0,7),data=createPlanningDemo(month),items=Object.values(data.comments),projects=Object.values(data.projects),members=Object.values(data.members);
 const card=p=><article className={`planning-card demo-project demo-project-${p.id}`} key={p.id}><div className="demo-cover"><span className="demo-cover-type">{p.id==='video'?'FILM / 02':p.id==='landing'?'DIGITAL / 03':'CAMPAIGN / 01'}</span><strong>{p.id==='video'?'Una historia.\nOtra perspectiva.':p.id==='landing'?'Ideas que\nconectan.':'El inicio de\nalgo nuevo.'}</strong><Icon name={p.id==='video'?'play':p.id==='landing'?'grid':'image'} size={28}/></div><div className="demo-project-body"><small>ESTUDIO NORTE · DEMO</small><h2>{p.name}</h2><p>{p.id==='video'?'Spot de producto · Versión 2':p.id==='landing'?'Experiencia web · Versión 3':'Identidad y carrusel · Versión 1'}</p><footer><span>{items.filter(c=>c.projectId===p.id).length} comentarios</span><span className="demo-review-status">En revisión</span></footer><button onClick={()=>setView('Revisión')}>Abrir revisión <Icon name="arrow"/></button></div></article>;
 return <div className="company-demo"><aside><h2>Estudio Norte</h2><small>Empresa ficticia</small><nav aria-label="Navegación demo">{['Inicio','Proyectos','Pauta','Planificación','Actividad','Equipo','Revisión'].map(name=><button key={name} aria-pressed={view===name} onClick={()=>setView(name)}>{name}</button>)}</nav><button onClick={onExit}>Salir de empresa activa</button></aside><main className="planning-page"><div className="demo-company-banner" role="status">DEMO · Empresa activa · Todos los datos son ficticios · Solo lectura <button onClick={onExit}>Volver a mi cuenta</button></div><h1>{view}</h1><p>Recorrido demostrativo de Estudio Norte. No crea archivos, tareas ni notificaciones en tu cuenta.</p>{view==='Inicio'&&<><h2>Una nueva ronda. Una mejor versión.</h2><p>{projects.length} proyectos · {items.length} comentarios este mes · {items.filter(c=>c.status==='open').length} abiertos</p><div className="planning-cards">{projects.map(card)}</div></>}{['Proyectos','Pauta'].includes(view)&&<><p>{view==='Pauta'?'Lanzamiento → Grupo de anuncios → Piezas · Publicación simulada, sin conexión con plataformas':''}</p><div className="planning-cards">{projects.map(card)}</div></>}{view==='Equipo'&&<div className="planning-cards">{members.map(m=><article className="planning-card" key={m.id}><span className="avatar">{m.initials}</span><h2>{m.name}</h2><p>Miembro ficticio · Revisor</p><small>No se envían invitaciones ni mensajes.</small></article>)}</div>}{view==='Planificación'&&<><h2>{month} · Mapa de comentarios ficticios</h2><div className="planning-grid">{Array.from({length:new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate()},(_,i)=>{const n=i+1,count=items.filter(c=>Number(c.createdAt.slice(8,10))===n).length;return <button className={`planning-day heat-${heatLevel(count,47)}`} key={n} aria-pressed={day===n} onClick={()=>setDay(n)}><strong>{n}</strong><span>{count} comentarios</span></button>})}</div><h2>Actividad del día {day}</h2></>}{['Actividad','Planificación','Revisión'].includes(view)&&<>{view==='Revisión'&&<div className="planning-card"><div className="demo-cover">▶ Spot de lanzamiento · V2</div><p>Vista ilustrativa de una pieza. No es un archivo reproducible ni permite anotaciones reales.</p></div>}<div className="planning-cards">{items.filter(c=>view!=='Planificación'||Number(c.createdAt.slice(8,10))===day).slice(0,12).map(c=><article className="planning-card" key={c.id}><small>{data.projects[c.projectId].name} · {c.status==='open'?'Abierto':'Resuelto'}</small><p>{c.text}</p><small>{data.members[c.authorId].name} · {c.createdAt.slice(0,10)}</small></article>)}</div><small>Se muestran hasta 12 ejemplos de comentarios.</small></>}</main></div>;
}
