import React, { useEffect, useState } from 'react';
import { PdfReview } from './PdfReview.jsx';

export function DocumentReview({media,page,setPage,onComment,renderAnnotations}){
  const [html,setHtml]=useState('');const [error,setError]=useState('');
  const [drawing,setDrawing]=useState(false);
  useEffect(()=>{let active=true;setError('');setHtml('');if(media.type==='html')fetch(media.url).then(r=>r.text()).then(text=>{if(active)setHtml(`<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'; font-src data:; form-action 'none'; base-uri 'none'">${text}`)}).catch(()=>{if(active)setError('No se pudo abrir el HTML')});return()=>{active=false}},[media.url,media.type]);
  return media.type==='pdf'?<PdfReview media={media} page={page} setPage={setPage} onComment={onComment} renderAnnotations={renderAnnotations}/>:<section className="document-review"><header><strong>{media.name}</strong>{media.type==='pdf'&&<label>Página del comentario<input type="number" min="1" max="10000" aria-label="Página del documento" value={page} onChange={e=>setPage(Math.max(1,Math.min(10000,Number(e.target.value)||1)))}/></label>}<button className="document-draw-toggle" aria-pressed={drawing} onClick={()=>setDrawing(value=>!value)}>{drawing?'Navegar documento':'Anotar sobre la vista'}</button></header><div className="document-scroll"><div className="document-sheet html-sheet">{media.type==='pdf'?<iframe key={page} title={`PDF ${media.name}, página ${page}`} src={`${media.url}#page=${page}`} />:media.type==='html'?error?<p role="alert">{error}</p>:html?<iframe title={`HTML aislado: ${media.name}`} sandbox="" srcDoc={html}/>:<p>Cargando HTML…</p>:<div className="document-unavailable"><h3>{media.type==='presentation'?'Presentación':'Documento'} listo para organizar</h3><p>La conversión de {media.extension} a páginas todavía no está conectada. Exporta a PDF y súbelo para revisar el contenido visualmente. Puedes dejar comentarios generales sobre este archivo.</p><a href={media.url} download={media.name}>Descargar original</a></div>}{renderAnnotations?.(drawing)}</div></div><small>{media.type==='html'?'Vista HTML fija de 1000 × 3000 px; marcas ancladas a esta superficie. Scripts y red bloqueados. Para contenido más largo, exporta a PDF.':media.type==='pdf'?'Selecciona aquí la página antes de anotar. En modo anotación se bloquea la navegación del visor; no desplaces el documento mientras dibujas.':''}</small></section>;
}
