import React,{useRef,useState,useId} from 'react';
import {useRonda} from '../state/RondaContext.jsx';
export default function MentionInput({value='',onChange,onKeyDown,...props}){
 const {state}=useRonda();const ref=useRef(null),id=useId();const [cursor,setCursor]=useState(0),[active,setActive]=useState(0),[dismissed,setDismissed]=useState(false);
 const match=value.slice(0,cursor).match(/(?:^|\s)@([^@\n]*)$/);const query=match?.[1]||'';
 const people=Object.values(state.members).filter(m=>m.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())).slice(0,6);
 const open=!!match&&!dismissed;
 const select=m=>{const from=cursor-query.length-1,insert='@'+m.name+' ';const next=value.slice(0,from)+insert+value.slice(cursor);if(props.maxLength&&next.length>props.maxLength)return;onChange({target:{value:next}});setDismissed(true);requestAnimationFrame(()=>{ref.current?.focus();ref.current?.setSelectionRange(from+insert.length,from+insert.length);setCursor(from+insert.length)})};
 return <div className="mention-editor"><textarea {...props} ref={ref} value={value} aria-controls={open?id:undefined} aria-expanded={open} onClick={e=>{setCursor(e.target.selectionStart);setDismissed(false)}} onChange={e=>{setCursor(e.target.selectionStart);setActive(0);setDismissed(false);onChange(e)}} onKeyDown={e=>{if(open){if(e.key==='Escape'){e.preventDefault();e.stopPropagation();setDismissed(true);return}if(people.length&&['ArrowDown','ArrowUp','Enter'].includes(e.key)&&!e.ctrlKey&&!e.metaKey){e.preventDefault();if(e.key==='Enter')select(people[Math.min(active,people.length-1)]);else setActive(i=>(i+(e.key==='ArrowDown'?1:-1)+people.length)%people.length);return}}onKeyDown?.(e)}}/>{open&&<div id={id} className="mention-menu" aria-label="Personas del equipo"><small>Mencionar a una persona</small>{people.map((m,i)=><button type="button" key={m.id} className={i===active?'active':''} onMouseDown={e=>e.preventDefault()} onClick={()=>select(m)}><span className="mention-avatar">{m.initials||m.name.slice(0,2)}</span><span><strong>{m.name}</strong><small>{m.role}</small></span></button>)}{!people.length&&<p>No hay personas con ese nombre.</p>}<small>Mención local · sin envío de correo</small></div>}</div>
}
