import React,{useState} from 'react';
const iso=d=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
export default function PautaDates({value=''}){
 const parsed=value.match(/^(\d{4}-\d{2}-\d{2}) → (\d{4}-\d{2}-\d{2})$/);
 const [start,setStart]=useState(parsed?.[1]||''),[end,setEnd]=useState(parsed?.[2]||''),[open,setOpen]=useState(false),[target,setTarget]=useState('start'),[month,setMonth]=useState(()=>{const d=parsed?new Date(parsed[1]+'T12:00:00'):new Date();return new Date(d.getFullYear(),d.getMonth(),1)});
 const offset=(month.getDay()+6)%7,count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();
 const choose=date=>{if(target==='start'){setStart(date);if(end&&end<date)setEnd('');setTarget('end')}else{setEnd(date);setOpen(false)}};
 return <fieldset className="pauta-dates"><legend>Fechas de pauta</legend><input type="hidden" name="Fechas" value={start&&end?start+' → '+end:!start&&!end?value:''}/><div className="date-inputs"><label>Inicio<input aria-label="Fecha de inicio" type="date" value={start} required={!!end} onChange={e=>{setStart(e.target.value);if(end<e.target.value)setEnd('')}}/></label><label>Fin<input aria-label="Fecha de fin" type="date" min={start||undefined} required={!!start} value={end} onChange={e=>setEnd(e.target.value)}/></label></div><button type="button" className="calendar-trigger" aria-expanded={open} onClick={()=>setOpen(v=>!v)}>▦ {open?'Cerrar calendario':'Elegir en calendario'}</button>{!parsed&&value&&!start&&<small>Fecha anterior conservada: {value}</small>}{open&&<div className="pauta-calendar" onKeyDown={e=>{if(e.key==='Escape')setOpen(false)}}><div className="calendar-target"><button type="button" aria-pressed={target==='start'} onClick={()=>setTarget('start')}>Inicio</button><button type="button" aria-pressed={target==='end'} onClick={()=>setTarget('end')}>Fin</button></div><header><button type="button" aria-label="Mes anterior" onClick={()=>setMonth(d=>new Date(d.getFullYear(),d.getMonth()-1,1))}>‹</button><strong>{month.toLocaleDateString('es-CO',{month:'long',year:'numeric'})}</strong><button type="button" aria-label="Mes siguiente" onClick={()=>setMonth(d=>new Date(d.getFullYear(),d.getMonth()+1,1))}>›</button></header><div className="calendar-grid">{['L','M','X','J','V','S','D'].map((d,i)=><span key={i} aria-hidden="true">{d}</span>)}{Array.from({length:offset},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:count},(_,i)=>{const date=iso(new Date(month.getFullYear(),month.getMonth(),i+1));return <button type="button" key={date} aria-label={'Elegir '+date} aria-pressed={date===start||date===end} disabled={target==='end'&&!!start&&date<start} className={start&&end&&date>start&&date<end?'in-range':''} onClick={()=>choose(date)}>{i+1}</button>})}</div><small>Selecciona {target==='start'?'el inicio':'el fin'} de la pauta. Fechas sin hora.</small></div>}</fieldset>
}
