import React,{useEffect,useRef,useState} from 'react';
import {getDocument,GlobalWorkerOptions} from 'pdfjs-dist';
import worker from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
GlobalWorkerOptions.workerSrc=worker;
export function PdfReview({media,page,setPage,onComment,renderAnnotations}){
 const [pdf,setPdf]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[drawing,setDrawing]=useState(false),[height,setHeight]=useState(1200);const canvas=useRef(null),scroll=useRef(null);
 useEffect(()=>{let active=true;setError('');setPdf(null);setLoading(true);const task=getDocument({url:media.url,isEvalSupported:false});task.promise.then(doc=>{if(active){setPdf(doc);setPage(1)}}).catch(()=>{if(active){setError('PDF protegido, dañado o no compatible.');setLoading(false)}});return()=>{active=false;task.destroy()}},[media.url]);
 useEffect(()=>{if(!pdf)return;let active=true,render;setLoading(true);setDrawing(false);scroll.current?.scrollTo(0,0);pdf.getPage(Math.min(page,pdf.numPages)).then(sheet=>{if(!active)return;const natural=sheet.getViewport({scale:1}),viewport=sheet.getViewport({scale:900/natural.width});setHeight(viewport.height);const el=canvas.current;el.width=viewport.width;el.height=viewport.height;render=sheet.render({canvasContext:el.getContext('2d'),viewport});return render.promise}).then(()=>{if(active)setLoading(false)}).catch(e=>{if(active&&e.name!=='RenderingCancelledException'){setError('Error al renderizar página');setLoading(false)}});return()=>{active=false;render?.cancel()}},[pdf,page]);
 return <section className="document-review"><header><strong>{media.name}</strong>{pdf&&<div className="document-pagination"><button disabled={page<=1} onClick={()=>setPage(page-1)}>Anterior</button><label>Página<input type="number" aria-label="Página PDF" min="1" max={pdf.numPages} value={page} onChange={e=>setPage(Math.max(1,Math.min(pdf.numPages,Number(e.target.value)||1)))}/> / {pdf.numPages}</label><button disabled={page>=pdf.numPages} onClick={()=>setPage(page+1)}>Siguiente</button></div>}<button className="document-draw-toggle" disabled={loading||!!error} aria-pressed={drawing} onClick={()=>setDrawing(v=>!v)}>{drawing?'Navegar':'Anotar página'}</button></header>{loading&&<p role="status">Preparando página…</p>}{error&&<p role="alert">{error}</p>}<div className="document-scroll" ref={scroll}><div className="document-sheet" style={{width:900,height,visibility:loading||error?'hidden':'visible'}}><canvas ref={canvas} aria-label={`Página ${page}`}/>{!loading&&!error&&renderAnnotations(drawing)}</div></div><small>Las figuras pertenecen a esta página y se desplazan junto con ella.</small></section>
}
