import React, { useEffect, useRef, useState } from 'react';
import { Heart, ChatBubble, Bookmark, RefreshDouble, SocialReferenceIcon } from './SocialReferenceIcons.jsx';
import { useRonda } from '../state/RondaContext.jsx';
import {resolveAssetVersion} from '../domain/asset-versions.js';
import { fileStore } from './DeliveryGrid.jsx';
import BaseIcon from './Icon.jsx';
import PreviewLikeCount from './PreviewLikeCount.jsx';
const Icon=props=>props.name==='send'?<SocialReferenceIcon {...props}/>:<BaseIcon {...props}/>;

function SocialMedia({asset, active, autoplay, ratio, onTime}) {
  const [url,setUrl]=useState(null),[error,setError]=useState(false); const video=useRef(null),container=useRef(null); const [visible,setVisible]=useState(false);
  useEffect(()=>{let live=true,objectUrl;setUrl(null);setError(false);fileStore(asset.fileId||asset.id).then(file=>{if(live){objectUrl=URL.createObjectURL(file);setUrl(objectUrl)}}).catch(()=>{if(live)setError(true)});return()=>{live=false;if(objectUrl)URL.revokeObjectURL(objectUrl)}},[asset.id,asset.fileId]);
  useEffect(()=>{const observer=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting),{threshold:.6});observer.observe(container.current);return()=>observer.disconnect()},[]);
  useEffect(()=>{const player=video.current;if(!player)return;if(active&&visible&&autoplay&&!matchMedia('(prefers-reduced-motion: reduce)').matches)player.play().catch(()=>{});else player.pause()},[active,visible,autoplay,url]);
  return <div ref={container} className="social-media" style={{aspectRatio:ratio}}>{error?<p role="alert">Média no disponible. Vuelve a seleccionar la lámina para reintentar.</p>:!url?<p>{active?'Cargando medio…':asset.name}</p>:asset.type==='image'?<img src={url} alt={asset.name} draggable={false}/>:<video ref={video} src={url} controls muted playsInline preload="metadata" onTimeUpdate={e=>active&&onTime(e.currentTarget.currentTime)} onError={()=>setError(true)}/>}</div>;
}

export default function SocialPreview({projectId,onSelect,onTime,onReview,onNotify}) {
  const {state,act}=useRonda(),project=state.projects[projectId];
  const saved=project?.socialPreview||{assetIds:[],account:state.workspace.branding?.name||'',caption:'',ratio:'4/5'};
  const [config,setConfig]=useState(saved),[editing,setEditing]=useState(!saved.assetIds.length),[autoplay,setAutoplay]=useState(false),[index,setIndex]=useState(0);
  const gesture=useRef(null);
  const eligible=(state.assets||[]).filter(a=>a.projectId===projectId&&['image','video'].includes(a.type)).map(asset=>resolveAssetVersion(state,asset));
  const items=saved.assetIds.map(id=>eligible.find(a=>a.id===id)).filter(Boolean); const selectRef=useRef(onSelect);selectRef.current=onSelect;
  const ids=items.map(a=>`${a.id}:${a.fileId}`).join('|');
  useEffect(()=>{if(index>=items.length){setIndex(0);return;}if(items[index])selectRef.current(items[index]);},[index,ids]);
  const step=offset=>setIndex(current=>(current+offset+items.length)%items.length);
  const distance=i=>{let d=i-index;if(items.length>2){if(d>items.length/2)d-=items.length;if(d< -items.length/2)d+=items.length;}return d;};
  function move(id,offset){const order=[...config.assetIds],from=order.indexOf(id),to=from+offset;if(to<0||to>=order.length)return;[order[from],order[to]]=[order[to],order[from]];setConfig({...config,assetIds:order})}
  const brandLogo=state.workspace.branding?.logo;
  return <section className={`social-preview ${brandLogo?'has-brand-logo':''}`} style={brandLogo?{'--brand-logo':`url("${brandLogo}")`}:undefined} aria-label="Preview social"><header className="social-heading"><div><strong>Preview social</strong><small>Simulación orientativa · No publica en Instagram</small></div><button onClick={()=>{setConfig(saved);setEditing(v=>!v)}}>{editing?'Cerrar configuración':'Configurar publicación'}</button></header>
    {editing&&<form className="social-config" onSubmit={e=>{e.preventDefault();act('social/save',{projectId,config});setEditing(false);onNotify('Preview configurada; guardado en curso')}}><label>Cuenta visible<input maxLength={80} value={config.account} placeholder="Tu marca" onChange={e=>setConfig({...config,account:e.target.value})}/></label><label>Texto de la publicación<textarea maxLength={2200} value={config.caption} onChange={e=>setConfig({...config,caption:e.target.value})}/></label><label>Formato<select value={config.ratio} onChange={e=>setConfig({...config,ratio:e.target.value})}><option value="1/1">Cuadrado · 1:1</option><option value="4/5">Vertical · 4:5</option><option value="16/9">Horizontal · 16:9</option></select></label><fieldset><legend>Medios y orden de este carrusel (máximo 20)</legend>{eligible.length?eligible.map(a=><label key={a.id}><input type="checkbox" checked={config.assetIds.includes(a.id)} disabled={!config.assetIds.includes(a.id)&&config.assetIds.length>=20} onChange={e=>setConfig({...config,assetIds:e.target.checked?[...config.assetIds,a.id]:config.assetIds.filter(id=>id!==a.id)})}/>{a.name}</label>):<p>Carga imágenes o videos en la parrilla para crear una publicación.</p>}</fieldset><ol>{config.assetIds.map((id,i)=><li key={id}><span>{eligible.find(a=>a.id===id)?.name||'Archivo no disponible'}</span><button type="button" disabled={!i} aria-label={`Mover lámina ${i+1} antes`} onClick={()=>move(id,-1)}>↑</button><button type="button" disabled={i===config.assetIds.length-1} aria-label={`Mover lámina ${i+1} después`} onClick={()=>move(id,1)}>↓</button></li>)}</ol><button className="studio-primary" disabled={!config.assetIds.length}>Guardar preview</button></form>}
    {!!items.length&&<><div className="social-deck" role="region" aria-roledescription="carrusel" aria-label="Publicación social y láminas vecinas" tabIndex={0} onKeyDown={e=>{if(e.target!==e.currentTarget)return;if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();step(e.key==='ArrowLeft'?-1:1)}}} onPointerDown={e=>{if(e.target.closest('button,video,input,textarea')||e.button!==0)return;gesture.current={x:e.clientX,y:e.clientY,id:e.pointerId};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerUp={e=>{const start=gesture.current;gesture.current=null;if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy))step(dx<0?1:-1)}} onPointerCancel={()=>{gesture.current=null}} onLostPointerCapture={()=>{gesture.current=null}} onDragStart={e=>e.preventDefault()}>{items.map((asset,i)=>{const d=distance(i),active=d===0;if(Math.abs(d)>1)return null;return <article key={asset.id} className={`social-post social-depth-card ${active?'is-central':'is-side'}`} style={{'--card-offset':d,zIndex:active?3:1}} aria-label={`Lámina ${i+1}: ${asset.name}`}><header aria-hidden={!active}><span className="social-avatar" aria-hidden="true">{(saved.account||project?.name||'R').slice(0,1).toUpperCase()}</span><strong>{saved.account||project?.name}</strong>{active&&<button aria-label="Editar publicación" onClick={()=>{setConfig(saved);setEditing(true)}}><Icon name="more"/></button>}</header><div className="social-image-zone"><SocialMedia asset={asset} active={active} ratio={saved.ratio} autoplay={autoplay} onTime={onTime}/>{!active?<button className="social-side-select" aria-label={`Seleccionar lámina ${i+1}`} onClick={()=>setIndex(i)}/>:<div className="social-overlay-navigation"><button aria-label="Lámina anterior" disabled={items.length<2} onClick={()=>step(-1)}><span style={{display:'flex',transform:'rotate(180deg)'}}><Icon name="chevron"/></span></button><div>{items.map((a,n)=><button key={a.id} aria-label={`Ver lámina ${n+1}`} aria-current={index===n?'true':undefined} onClick={()=>setIndex(n)}><span/></button>)}</div><button aria-label="Lámina siguiente" disabled={items.length<2} onClick={()=>step(1)}><Icon name="chevron"/></button></div>}</div><footer aria-hidden={!active}><div className="social-reactions" aria-label="Iconos y 325 me gusta de demostración; no son métricas de Instagram"><Heart aria-hidden="true"/><PreviewLikeCount active={active}/><ChatBubble aria-hidden="true"/><RefreshDouble aria-hidden="true"/><Icon name="send" size={24}/><Bookmark aria-hidden="true" className="social-bookmark"/></div>{saved.caption&&<p className="social-caption"><strong>{saved.account||project?.name}</strong> {saved.caption}</p>}</footer></article>})}</div><span className="visually-hidden" aria-live="polite">Lámina {index+1} de {items.length}</span></>}
    {editing&&!!items.length&&<div className="social-editor-actions"><label><input type="checkbox" checked={autoplay} onChange={e=>setAutoplay(e.target.checked)}/>Autoplay del video visible, sin sonido</label><button onClick={()=>onReview(items[index])}>Anotar esta lámina en el visor completo</button><small>Esta simulación recorta el medio para llenar la tarjeta; no modifica el original. Sin métricas ni publicación en Instagram.</small></div>}
    {!items.length&&!editing&&<p>No hay medios configurados para esta publicación.</p>}
  </section>;
}
